### ISSUE TITLE
Add a function to stop the music.

### ISSUE THREAD

**Issue by 28klotlucas2** [timo-reymann/python-script-background-music#1]
I have a command line utility that you can run commands in without having to reopen the program every time. I want to add background music that can be stopped when the script is done.

**Comment by timo-reymann** [comment]
A bit trickier than expected, because of the way playsound works (which this package is based on). Currently, the thread running the music is in daemon mode, so it's exiting with the application. When using a context manager, this gets a lot trickier.

Will have to figure something out, but this package has not the highest priority, so please bear with me :)

**Comment by timo-reymann** [comment]
Okay found a nice workaround, killing subprocesses manually. Works flawless on macOS, can't test on Windows anyways.

For Linux, it should also work since it uses playbin which creates a subprocess as well.

**Comment by timo-reymann** [comment]
Please test with 1.3.0 if it works for you, then I will close this ticket.

**Comment by timo-reymann** [comment]
:heavy_check_mark: Verified on linux

**Comment by msr8** [comment]
Hey if you dont mind, can you please link me the lines you used to achieve this? I tried to find a solution for HOURS when I was working on a project that needed that functionality, but ultimately gave up

**Comment by timo-reymann** [comment]
Heya @msr8 sure :) 

https://github.com/timo-reymann/python-script-background-music/commit/d5dd9a97b98182423af9751b352fd6bb3d077b25#diff-1a59a203d9924032c28f66ea8f97966c0d9acf9eddf46a8f54a6ca9cf48e966aR11

Basically 
- get the PID of the thread from the OS
- reap all child processes 
- after that regular terminate. 
 
The problem I faced: When the child processes are not killed beforehand, they simply run without the parent process.

**Comment by timo-reymann** [comment]
Closing this for now as everything works well :) - if you have any concerns etc. feel free to reopen this issue with a comment or create a new one.
